In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### one dimension array

In [24]:
import numpy as np
arr1=np.array([4,3,2,6,4])
print(arr1)
print(type(arr1))   # datatype
print(arr1.shape)   # shape of the array
print(arr1.size)    # no. of elements in array
print(arr1.ndim)    # dimension of an array
print(arr1.dtype)   # datatype of elements in array
print(arr1.itemsize)

[4 3 2 6 4]
<class 'numpy.ndarray'>
(5,)
5
1
int64
8


### two dimension array

In [22]:
arr2=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,1,2,3]])
print(arr2)
print(type(arr2))   # datatype
print(arr2.shape)   # shape of the array
print(arr2.size)    # no. of elements in array
print(arr2.ndim)    # dimension of an array
print(arr2.dtype)   # datatype of elements in array
print(arr1.itemsize)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
<class 'numpy.ndarray'>
(3, 4)
12
2
int64
8


In [15]:
# reshape
arr1.reshape(1,5)

array([[4, 3, 2, 6, 4]])

### create an array with range 

In [20]:
x=np.arange(0,10,2)
y=np.arange(0,10,2).reshape(1,5)
z=np.arange(0,10,2).reshape(5,1)
print(x)
print(y)
print(z)

[0 2 4 6 8]
[[0 2 4 6 8]]
[[0]
 [2]
 [4]
 [6]
 [8]]


### Array creation

In [26]:
arr1=np.array([3,5,1,3,4])
print(arr1)

[3 5 1 3 4]


In [32]:
# default values(zero)

arr1=np.zeros(5)
arr2=np.zeros((5,5))
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
# ones

arr=np.ones(4)
arr1=np.ones((5,5))
print(arr)
print(arr1)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
# identitiy matrices

arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
# default with specific number

arr1=np.full((3),3)
print(arr1)
arr2=np.full((3,4),8)
print(arr2)

[3 3 3]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


### type casting

In [43]:
arr1=np.array([4.3,2.9,5.1,1.3])
print(arr1.astype(int))

[4 2 5 1]


### numpy array vectorised operation

In [45]:
arr1=np.array([3,4,1,3,5,3,3])
arr2=np.array([45,2,33,12,34,54,34])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)

[48  6 34 15 39 57 37]
[-42   2 -32  -9 -29 -51 -31]
[135   8  33  36 170 162 102]
[0.06666667 2.         0.03030303 0.25       0.14705882 0.05555556
 0.08823529]
[0 2 0 0 0 0 0]


In [52]:
arr=np.array([45,2,34,12,56,43,5,6,6])
print(arr+10)
print(arr-10)
print(arr*10)
print(arr/10)
print(arr//10)
print(arr**10)

[55 12 44 22 66 53 15 16 16]
[35 -8 24  2 46 33 -5 -4 -4]
[450  20 340 120 560 430  50  60  60]
[4.5 0.2 3.4 1.2 5.6 4.3 0.5 0.6 0.6]
[4 0 3 1 5 4 0 0 0]
[ 34050628916015625               1024   2064377754059776
        61917364224 303305489096114176  21611482313284249
            9765625           60466176           60466176]


### universal function

In [50]:
arr1=np.array([4,2,5,7,1,2,3])
print(np.sqrt(arr1))  # sruare root
print(np.exp(arr1))   # exponential
print(np.sin(arr1))   # sine value
print(np.log(arr1))   # logarithm

[2.         1.41421356 2.23606798 2.64575131 1.         1.41421356
 1.73205081]
[  54.59815003    7.3890561   148.4131591  1096.63315843    2.71828183
    7.3890561    20.08553692]
[-0.7568025   0.90929743 -0.95892427  0.6569866   0.84147098  0.90929743
  0.14112001]
[1.38629436 0.69314718 1.60943791 1.94591015 0.         0.69314718
 1.09861229]


### accessing the elements

In [54]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
print(arr[0])

[1 2 3 4]


In [57]:
print(arr[0][0])

1


In [59]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [60]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


### modify

In [61]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [62]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [67]:
# fancy indexing

arr=np.array([10,20,30,40,50,60,70,80])
print(arr[[0,2,4,6]])

[10 30 50 70]


In [68]:
# boolean masking

print(arr[arr>25])

[30 40 50 60 70 80]


### Aggregate function

In [70]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

550
10
100
55.0
55.0
28.722813232690143
825.0


### Statistical concept=Normalization(to have a mean of 0 and standard deviation of 1)

In [71]:
mean=np.mean(arr)
std_dev=np.std(arr)

#normalize the data
normalized_data=(arr-mean)/std_dev
print(normalized_data)

[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


### logical operation

In [76]:
arr>50

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[arr>50]

array([ 60,  70,  80,  90, 100])

In [79]:
arr[(arr>=50) & (arr<=90)]

array([50, 60, 70, 80, 90])

### flatten

In [82]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [85]:
arr=np.array([10,20,30,40,50,60])
print(arr)
reshaped_arr=arr.reshape(2,3)
print(reshaped_arr)

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


### Modification

In [86]:
arr=np.array([10,20,30,40,50,60])
arr1=np.append(arr,[70,80,90])
print(arr1)

[10 20 30 40 50 60 70 80 90]


In [93]:
arr=np.array([10,20,30,40,50,60])
arra=np.array([70,80,90,100,110,120])

new_arr=np.concatenate((arr,arra))
print(new_arr)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [94]:
arr1=np.array([[1,2],
              [3,4]])
arr2=np.array([[1,2],
              [3,4]])
new_arr=np.concatenate((arr1,arr2),axis=0)
print(new_arr)
new_arr=np.concatenate((arr1,arr2),axis=1)
print(new_arr)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]


In [95]:
#one dimensional
arr=np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.insert(arr,3,100)
print(new_arr)

# two dimensional(row wise)
arr_2d=np.array([[1,2,3],
               [4,5,6]])
print(arr_2d)
new_arra=np.insert(arr_2d,1,[5,6,7],axis=0)
print(new_arra)

# two dimensional(row wise)
new_ara=np.insert(arr_2d,1,[5,6],axis=1)
print(new_ara)

#in one line(flatten)
ne_ara=np.insert(arr_2d,1,[5,6],axis=None)
print(ne_ara)

[10 20 30 40 50 60]
[ 10  20  30 100  40  50  60]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 6 7]
 [4 5 6]]
[[1 5 2 3]
 [4 6 5 6]]
[1 5 6 2 3 4 5 6]


In [98]:
# removing

arr=np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.delete(arr,0)
print(new_arr)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
new_arra=np.delete(arr_2d,0,axis=0)
print(new_arra)
new_arra=np.delete(arr_2d,0,axis=1)
print(new_arra)

[10 20 30 40 50 60]
[20 30 40 50 60]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[[2 3]
 [5 6]]


In [102]:
# splitting

arr=np.array([10,20,30,40,50,60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]


In [103]:
# stacking

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### broadcasting

In [104]:
prices=np.array([100,200,300])
discount=10 #scalar single value
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


### vectorization

In [108]:
# normal python
list1=[1,2,3]
list2=[4,5,6]

result=[x+y for x,y in zip(list1,list2)]
print(result)

[5, 7, 9]


In [106]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

result=arr1+arr2
print(result)

[5 7 9]


In [107]:
arr1=np.array([1,2,3])

result=arr1*3
print(result)

[3 6 9]


### handling missing values

In [110]:
arr=np.array([1,2,np.inf,4,-np.inf,5])
print(np.isinf(arr))

cleared=np.nan_to_num(arr,posinf=1000,neginf=-1000)
print(cleared)

[False False  True False  True False]
[    1.     2.  1000.     4. -1000.     5.]


In [111]:
arr=np.array([1,2,3,np.nan])
print(np.isnan(arr))

[False False False  True]


In [116]:
arr=np.array([1,2,3,np.nan,5])
print(arr)
clear=np.nan_to_num(arr)  # default value=0
print(clear)
cleared=np.nan_to_num(arr,nan=4)
print(cleared)

[ 1.  2.  3. nan  5.]
[1. 2. 3. 0. 5.]
[1. 2. 3. 4. 5.]
